services:
  api-keys:
    image:
      redis:7.0.4-alpine
    ports: 
      - 6380:6379

  rooms:
    image:
      redis:7.0.4-alpine
    ports: 
      - 6379:6380

  media-nodes:
    image:
      redis:7.0.4-alpine
    ports: 
      - 6379:6379

  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
